# Generated by Django 6.0.4 on 2026-05-03 23:57

import apps.accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='full name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('role', models.CharField(choices=[('member', 'Member'), ('realtor', 'Realtor'), ('vendor', 'Vendor'), ('staff', 'Staff'), ('admin', 'Admin')], default='member', max_length=12)),
                ('is_realtor', models.BooleanField(db_index=True, default=False)),
                ('is_vendor', models.BooleanField(db_index=True, default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RealtorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(db_index=True, max_length=32)),
                ('license_type', models.CharField(choices=[('broker', 'Broker'), ('managing_broker', 'Managing Broker'), ('designated_broker', 'Designated Broker'), ('branch_manager', 'Branch Manager')], default='broker', max_length=24)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('not_found', 'Not found'), ('error', 'Error')], db_index=True, default='pending', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('license_expires', models.DateField(blank=True, null=True)),
                ('brokerage', models.CharField(blank=True, max_length=200)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='realtors/')),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Realtor profile',
                'verbose_name_plural': 'Realtor profiles',
            },
        ),
        migrations.CreateModel(
            name='LicenseCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=24)),
                ('raw_response', models.JSONField(default=dict)),
                ('source', models.CharField(default='arello', max_length=24)),
                ('triggered_by', models.CharField(choices=[('signup', 'Signup'), ('scheduled', 'Scheduled (Celery beat)'), ('manual', 'Manual recheck')], default='signup', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='accounts.realtorprofile')),
            ],
            options={
                'verbose_name': 'License check',
                'verbose_name_plural': 'License checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended')], default='draft', max_length=12)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor profile',
                'verbose_name_plural': 'Vendor profiles',
            },
        ),
    ]
