# Generated by Django 6.0.4 on 2026-05-04 06:11

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtorprofile',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='realtors/', validators=[apps.core.validators.MaxFileSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.core.validators.MaxFileSizeValidator(5)]),
        ),
    ]
