# Generated by Django 6.0.4 on 2026-05-04 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=600)),
                ('price_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_high', models.DecimalField(decimal_places=2, help_text='Equal to price_low for fixed pricing', max_digits=10)),
                ('delivery_days', models.PositiveIntegerField(default=7)),
                ('revisions', models.PositiveIntegerField(default=1)),
                ('features', models.JSONField(blank=True, default=list, help_text='["item 1", "item 2"]')),
            ],
            options={
                'ordering': ['service', 'price_low'],
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('removed', 'Removed'), ('shadow', 'Shadow-banned')], db_index=True, default='pending', max_length=10)),
                ('moderation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cadence', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('min_term_months', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='accounts.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='pending', max_length=10)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='marketplace.bundle')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads_sent', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='accounts.vendorprofile')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='marketplace.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=4000)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.lead')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('removed', 'Removed'), ('shadow', 'Shadow-banned')], db_index=True, default='pending', max_length=10)),
                ('moderation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(max_length=4000)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='marketplace/services/')),
                ('response_time_hours', models.PositiveIntegerField(default=24, help_text='Promised response time')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='marketplace.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='marketplace.service'),
        ),
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='marketplace.service'),
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_per_period', models.PositiveIntegerField(default=1)),
                ('fulfillment_note', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.bundle')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_bundles', to='marketplace.service')),
            ],
            options={
                'ordering': ['bundle', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('removed', 'Removed'), ('shadow', 'Shadow-banned')], db_index=True, default='pending', max_length=10)),
                ('moderation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField(max_length=2000)),
                ('vendor_response', models.TextField(blank=True, max_length=2000)),
                ('vendor_response_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_in_range')],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active', 'moderation_status'], name='marketplace_categor_89e34a_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['vendor'], name='marketplace_vendor__ce9879_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('service', 'tier')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['vendor', 'status', '-created_at'], name='marketplace_vendor__a36d03_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['buyer', '-created_at'], name='marketplace_buyer_i_ebaf3c_idx'),
        ),
    ]
