# Generated by Django 6.0.4 on 2026-05-04 06:11

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/services/', validators=[apps.core.validators.MaxFileSizeValidator(10)]),
        ),
    ]
