# Generated by Django 6.0.4 on 2026-05-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_leadmessage_moderatable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leadmessage',
            new_name='marketplace_lead_id_7b0ba3_idx',
            old_name='mp_leadmsg_lead_idx',
        ),
        migrations.RenameIndex(
            model_name='leadmessage',
            new_name='marketplace_moderat_b4f806_idx',
            old_name='mp_leadmsg_modstat_idx',
        ),
    ]
