# Generated by Django 6.0.4 on 2026-05-04 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Newsletter subscription',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('removed', 'Removed'), ('shadow', 'Shadow-banned')], db_index=True, default='pending', max_length=10)),
                ('moderation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('org', 'Yakima Web (org-authored)'), ('blog', 'Realtor blog'), ('landing', 'Lead-magnet landing')], db_index=True, default='blog', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('excerpt', models.CharField(blank=True, help_text='Shown on cards + meta description.', max_length=300)),
                ('body', models.TextField(help_text='Markdown — will be sanitized.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='content/hero/')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('removed', 'Removed'), ('shadow', 'Shadow-banned')], db_index=True, default='pending', max_length=10)),
                ('moderation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(max_length=4000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], db_index=True, max_length=12)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('short', 'Short / Reel'), ('post', 'Post')], max_length=8)),
                ('external_id', models.CharField(help_text='YouTube video ID, IG post shortcode, etc.', max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('thumb_url', models.URLField(blank=True)),
                ('canonical_url', models.URLField()),
                ('embed_html', models.TextField(blank=True, help_text='Cached safe iframe HTML (refreshed by beat task).')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('last_refreshed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Social embed',
                'ordering': ['-is_pinned', '-published_at', 'sort_order'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_social_embed')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'status', '-published_at'], name='content_pos_post_ty_eba4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'moderation_status', 'created_at'], name='content_com_post_id_c0b50d_idx'),
        ),
    ]
