# Generated by Django 6.0.4 on 2026-05-04 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('model_id', models.CharField(help_text='e.g. gemini-2.5-flash-image, gemini-2.5-pro', max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('cost_per_run_estimate_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('member_daily_limit', models.PositiveIntegerField(default=10)),
                ('realtor_daily_limit', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='ToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked (moderation/rate-limit/spend-cap)')], db_index=True, default='queued', max_length=10)),
                ('input_meta', models.JSONField(default=dict)),
                ('output_meta', models.JSONField(default=dict)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('error', models.TextField(blank=True)),
                ('block_reason', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='tools.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool usage',
                'verbose_name_plural': 'Tool usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'tool', 'created_at'], name='tools_toolu_user_id_1d6756_idx'), models.Index(fields=['status', 'created_at'], name='tools_toolu_status_4eaad2_idx')],
            },
        ),
    ]
