# Generated by Django 6.0.4 on 2026-05-03 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_id', models.PositiveBigIntegerField(null=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('off_topic', 'Off-topic'), ('doxxing', 'Doxxing / personal info'), ('fraud', 'Fraud / misrepresentation'), ('other', 'Other')], max_length=12)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], db_index=True, default='open', max_length=10)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_id', models.PositiveBigIntegerField(null=True)),
                ('layer', models.CharField(choices=[('deterministic', 'Deterministic'), ('ai', 'AI'), ('human', 'Human')], max_length=14)),
                ('classifier_ver', models.CharField(default='moderation_v1', max_length=32)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('output', models.JSONField(default=dict)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('queue', 'Queue for human'), ('remove', 'Remove'), ('shadow', 'Shadow-ban')], max_length=8)),
                ('severity', models.PositiveSmallIntegerField(null=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_decisions', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Moderation decision',
                'verbose_name_plural': 'Moderation decisions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='moderation__target__82a27a_idx'), models.Index(fields=['action'], name='moderation__action_db0277_idx')],
            },
        ),
    ]
