# Generated by Django 6.0.4 on 2026-05-04 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('color', models.CharField(default='gold', help_text='Tailwind color name: gold/ok/warn/err/mist', max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('removed', 'Removed'), ('shadow', 'Shadow-banned')], db_index=True, default='pending', max_length=10)),
                ('moderation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('body', models.TextField(max_length=10000)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('pinned', models.BooleanField(db_index=True, default=False)),
                ('locked', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to=settings.AUTH_USER_MODEL)),
                ('flair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='forum.flair')),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('removed', 'Removed'), ('shadow', 'Shadow-banned')], db_index=True, default='pending', max_length=10)),
                ('moderation_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(max_length=10000)),
                ('score', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.forumreply')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumthread')),
            ],
            options={
                'ordering': ['-score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveBigIntegerField()),
                ('value', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['flair', '-created_at'], name='forum_forum_flair_i_1bd27f_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['-score'], name='forum_forum_score_4df51b_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['target_type', 'target_id'], name='forum_vote_target__ccf701_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('target_type', 'target_id', 'voter'), name='unique_vote_per_user_target'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='vote_value_in_range'),
        ),
    ]
