# Generated by Django 6.0.4 on 2026-05-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_05b4bc_idx',
            old_name='notif_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_47e85c_idx',
            old_name='notif_user_read_idx',
        ),
    ]
